apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: frr
spec:
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  bgpInstances:
  - name: instance-64512
    localASN: 64512
    localPort: 179
    peers:
    - name: peer-64512-frr
      peerASN: 64512
      peerAddress: 172.18.0.6
      peerConfigRef:
        name: peer-config
