apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsmyip
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: whatsmyip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whatsmyip
    spec:
      containers:
        - name: whatsmyip
          image: quay.io/isovalent-dev/egressgw-whatismyip:latest
          ports:
            - containerPort: 8000

